name: Web Deployment

on:
  push:
    branches:
      - main  # Workflow jalan tiap kali kamu push ke branch main

jobs:
  web-deploy:
    name: Deploying to Hosting
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Jika file website kamu ada di folder tertentu (misal: 'public'), 
          # ganti '.' di bawah ini jadi 'public'
          local-dir: ./ 
          # Jika di hosting harus masuk ke folder public_html
          server-dir: ./public_html/
